# ---------------------------------------------------------------
# Copyright (c) 2021, NVIDIA Corporation. All rights reserved.
#
# This work is licensed under the NVIDIA Source Code License
# ---------------------------------------------------------------
import math
import warnings
import numpy as np
from functools import partial

import torch
import torch.nn as nn
import os

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    """Fill a tensor with truncated-normal values without tracking gradients.

    Args:
        tensor: Tensor to initialize in place.
        mean: Mean of the source normal distribution.
        std: Standard deviation of the source normal distribution.
        a: Lower truncation bound.
        b: Upper truncation bound.

    Returns:
        The input tensor after in-place initialization.
    """
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        """Compute the standard normal cumulative distribution function.

        Args:
            x: Scalar input value.

        Returns:
            Cumulative probability for the standard normal distribution.
        """
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""
    Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Returns:
        The input tensor after in-place truncated-normal initialization.
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

class GELU(nn.Module):
    """Gaussian Error Linear Unit using the tanh approximation."""

    def __init__(self):
        """Create a GELU activation module.

        Args:
            None.

        Returns:
            None.
        """
        super(GELU, self).__init__()

    def forward(self, x):
        """Apply GELU activation.

        Args:
            x: Input tensor.

        Returns:
            Activated tensor with the same shape as ``x``.
        """
        return 0.5 * x * (1 + torch.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * torch.pow(x,3))))

class OverlapPatchEmbed(nn.Module):
    """Overlapping patch embedding layer used by MiT/SegFormer."""

    def __init__(self, patch_size=7, stride=4, in_chans=3, embed_dim=768):
        """Create an overlapping patch embedding module.

        Args:
            patch_size: Spatial convolution kernel size.
            stride: Spatial convolution stride.
            in_chans: Number of input image channels.
            embed_dim: Number of output embedding channels.

        Returns:
            None.
        """
        super().__init__()
        patch_size  = (patch_size, patch_size)
        self.proj   = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=stride,
                              padding=(patch_size[0] // 2, patch_size[1] // 2))
        self.norm   = nn.LayerNorm(embed_dim)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize module weights.

        Args:
            m: Module instance visited by ``Module.apply``.

        Returns:
            None.
        """
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x):
        """Convert an image feature map into patch tokens.

        Args:
            x: Input tensor with shape ``[B, C, H, W]``.

        Returns:
            Tuple ``(tokens, H_out, W_out)`` where tokens have shape
            ``[B, H_out*W_out, embed_dim]``.
        """
        x = self.proj(x)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)
        x = self.norm(x)

        return x, H, W

class Attention(nn.Module):
    """Spatial-reduction multi-head self-attention used by MiT."""

    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0., sr_ratio=1):
        """Create a spatial-reduction attention module.

        Args:
            dim: Token embedding dimension.
            num_heads: Number of attention heads.
            qkv_bias: Whether query/key/value projections use bias.
            qk_scale: Optional custom query-key scale.
            attn_drop: Dropout probability for attention weights.
            proj_drop: Dropout probability after the output projection.
            sr_ratio: Spatial-reduction ratio for key/value tokens.

        Returns:
            None.
        """
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."

        self.dim        = dim
        self.num_heads  = num_heads
        head_dim        = dim // num_heads
        self.scale      = qk_scale or head_dim ** -0.5

        self.q          = nn.Linear(dim, dim, bias=qkv_bias)
        
        self.sr_ratio = sr_ratio
        if sr_ratio > 1:
            self.sr     = nn.Conv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
            self.norm   = nn.LayerNorm(dim)
        self.kv         = nn.Linear(dim, dim * 2, bias=qkv_bias)
        
        self.attn_drop  = nn.Dropout(attn_drop)
        
        self.proj       = nn.Linear(dim, dim)
        self.proj_drop  = nn.Dropout(proj_drop)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize module weights.

        Args:
            m: Module instance visited by ``Module.apply``.

        Returns:
            None.
        """
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        """Apply spatial-reduction self-attention.

        Args:
            x: Token tensor with shape ``[B, N, C]``.
            H: Token grid height before flattening.
            W: Token grid width before flattening.

        Returns:
            Attention output tensor with shape ``[B, N, C]``.
        """
        B, N, C = x.shape
        # Project tokens to queries and split channels into attention heads.
        q = self.q(x).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)

        if self.sr_ratio > 1:
            # Restore token layout, reduce the spatial grid, and re-flatten.
            x_ = x.permute(0, 2, 1).reshape(B, C, H, W)
            x_ = self.sr(x_).reshape(B, C, -1).permute(0, 2, 1)
            x_ = self.norm(x_)
            kv = self.kv(x_).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        else:
            kv = self.kv(x).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        k, v = kv[0], kv[1]

        # Query-key similarity produces attention weights over reduced tokens.
        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        # Weighted values are merged back from heads to the original channel dimension.
        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x

def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    """Apply per-sample stochastic depth.

    Args:
        x: Input tensor.
        drop_prob: Probability of dropping the residual path.
        training: Whether stochastic depth is active.
        scale_by_keep: Whether to divide kept paths by keep probability.

    Returns:
        Tensor after stochastic-depth masking.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob       = 1 - drop_prob
    shape           = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor   = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor

class DropPath(nn.Module):
    """Module wrapper for stochastic depth."""

    def __init__(self, drop_prob=None, scale_by_keep=True):
        """Create a DropPath module.

        Args:
            drop_prob: Probability of dropping the residual path.
            scale_by_keep: Whether to divide kept paths by keep probability.

        Returns:
            None.
        """
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        """Apply stochastic depth to an input tensor.

        Args:
            x: Input tensor.

        Returns:
            Tensor after stochastic-depth masking.
        """
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)
    
class DWConv(nn.Module):
    """Depth-wise convolution over token grids."""

    def __init__(self, dim=768):
        """Create a depth-wise convolution module.

        Args:
            dim: Number of token channels.

        Returns:
            None.
        """
        super(DWConv, self).__init__()
        self.dwconv = nn.Conv2d(dim, dim, 3, 1, 1, bias=True, groups=dim)

    def forward(self, x, H, W):
        """Apply depth-wise convolution to flattened tokens.

        Args:
            x: Token tensor with shape ``[B, N, C]``.
            H: Token grid height.
            W: Token grid width.

        Returns:
            Token tensor with shape ``[B, N, C]``.
        """
        B, N, C = x.shape
        x = x.transpose(1, 2).view(B, C, H, W)
        x = self.dwconv(x)
        x = x.flatten(2).transpose(1, 2)

        return x
    
class Mlp(nn.Module):
    """Transformer feed-forward network with depth-wise convolution."""

    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=GELU, drop=0.):
        """Create a Mix-FFN block.

        Args:
            in_features: Number of input token channels.
            hidden_features: Number of hidden token channels. Defaults to
                ``in_features`` when omitted.
            out_features: Number of output token channels. Defaults to
                ``in_features`` when omitted.
            act_layer: Activation module class.
            drop: Dropout probability.

        Returns:
            None.
        """
        super().__init__()
        out_features    = out_features or in_features
        hidden_features = hidden_features or in_features
        
        self.fc1    = nn.Linear(in_features, hidden_features)
        self.dwconv = DWConv(hidden_features)
        self.act    = act_layer()
        
        self.fc2    = nn.Linear(hidden_features, out_features)
        
        self.drop   = nn.Dropout(drop)

        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize module weights.

        Args:
            m: Module instance visited by ``Module.apply``.

        Returns:
            None.
        """
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        """Apply the Mix-FFN block.

        Args:
            x: Token tensor with shape ``[B, N, C]``.
            H: Token grid height.
            W: Token grid width.

        Returns:
            Token tensor with shape ``[B, N, C]``.
        """
        x = self.fc1(x)
        x = self.dwconv(x, H, W)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)
        x = self.drop(x)
        return x

class Block(nn.Module):
    """MiT transformer block with attention, Mix-FFN, and residual paths."""

    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=GELU, norm_layer=nn.LayerNorm, sr_ratio=1):
        """Create one MiT transformer block.

        Args:
            dim: Token embedding dimension.
            num_heads: Number of attention heads.
            mlp_ratio: Expansion ratio for the feed-forward hidden dimension.
            qkv_bias: Whether query/key/value projections use bias.
            qk_scale: Optional custom query-key scale.
            drop: Dropout probability for projections and feed-forward layers.
            attn_drop: Dropout probability for attention weights.
            drop_path: Stochastic-depth probability.
            act_layer: Activation module class.
            norm_layer: Normalization module class.
            sr_ratio: Spatial-reduction ratio for attention.

        Returns:
            None.
        """
        super().__init__()
        self.norm1      = norm_layer(dim)
        
        self.attn       = Attention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale,
            attn_drop=attn_drop, proj_drop=drop, sr_ratio=sr_ratio
        )
        self.norm2      = norm_layer(dim)
        self.mlp        = Mlp(in_features=dim, hidden_features=int(dim * mlp_ratio), act_layer=act_layer, drop=drop)

        self.drop_path  = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        
        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize module weights.

        Args:
            m: Module instance visited by ``Module.apply``.

        Returns:
            None.
        """
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x, H, W):
        """Apply attention and feed-forward residual updates.

        Args:
            x: Token tensor with shape ``[B, N, C]``.
            H: Token grid height.
            W: Token grid width.

        Returns:
            Token tensor with shape ``[B, N, C]``.
        """
        x = x + self.drop_path(self.attn(self.norm1(x), H, W))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W))
        return x

class MixVisionTransformer(nn.Module):
    """MixVisionTransformer backbone used by SegFormer."""

    def __init__(self, in_chans=3, num_classes=1000, embed_dims=[32, 64, 160, 256],
                 num_heads=[1, 2, 4, 8], mlp_ratios=[4, 4, 4, 4], qkv_bias=False, qk_scale=None, drop_rate=0.,
                 attn_drop_rate=0., drop_path_rate=0., norm_layer=nn.LayerNorm,
                 depths=[3, 4, 6, 3], sr_ratios=[8, 4, 2, 1]):
        """Create a four-stage MixVisionTransformer.

        Args:
            in_chans: Number of input image channels.
            num_classes: Reserved classification class count.
            embed_dims: Embedding dimensions for the four stages.
            num_heads: Attention head counts for the four stages.
            mlp_ratios: Feed-forward expansion ratios for the four stages.
            qkv_bias: Whether query/key/value projections use bias.
            qk_scale: Optional custom query-key scale.
            drop_rate: Dropout probability for projections and feed-forward layers.
            attn_drop_rate: Dropout probability for attention weights.
            drop_path_rate: Maximum stochastic-depth probability.
            norm_layer: Normalization module class.
            depths: Number of transformer blocks per stage.
            sr_ratios: Spatial-reduction ratios per stage.

        Returns:
            None.
        """
        super().__init__()
        self.num_classes    = num_classes
        self.depths         = depths

        # Create a linearly increasing stochastic-depth rate across all blocks.
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]
        
        # Stage 1: overlap patch embedding followed by transformer blocks.
        self.patch_embed1 = OverlapPatchEmbed(patch_size=7, stride=4, in_chans=in_chans, embed_dim=embed_dims[0])
        cur = 0
        self.block1 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[0], num_heads=num_heads[0], mlp_ratio=mlp_ratios[0], qkv_bias=qkv_bias, qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer, sr_ratio=sr_ratios[0]
                )
                for i in range(depths[0])
            ]
        )
        self.norm1 = norm_layer(embed_dims[0])
        
        # Stage 2: downsample stage-1 features and refine tokens.
        self.patch_embed2 = OverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[0], embed_dim=embed_dims[1])
        cur += depths[0]
        self.block2 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[1], num_heads=num_heads[1], mlp_ratio=mlp_ratios[1], qkv_bias=qkv_bias, qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer, sr_ratio=sr_ratios[1]
                )
                for i in range(depths[1])
            ]
        )
        self.norm2 = norm_layer(embed_dims[1])

        # Stage 3: downsample stage-2 features and refine tokens.
        self.patch_embed3 = OverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[1], embed_dim=embed_dims[2])
        cur += depths[1]
        self.block3 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[2], num_heads=num_heads[2], mlp_ratio=mlp_ratios[2], qkv_bias=qkv_bias, qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer, sr_ratio=sr_ratios[2]
                )
                for i in range(depths[2])
            ]
        )
        self.norm3 = norm_layer(embed_dims[2])

        # Stage 4: downsample stage-3 features and produce semantic features.
        self.patch_embed4 = OverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[2], embed_dim=embed_dims[3])
        cur += depths[2]
        self.block4 = nn.ModuleList(
            [
                Block(
                    dim=embed_dims[3], num_heads=num_heads[3], mlp_ratio=mlp_ratios[3], qkv_bias=qkv_bias, qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer, sr_ratio=sr_ratios[3]
                )
                for i in range(depths[3])
            ]
        )
        self.norm4 = norm_layer(embed_dims[3])

        self.apply(self._init_weights)

    def _init_weights(self, m):
        """Initialize module weights.

        Args:
            m: Module instance visited by ``Module.apply``.

        Returns:
            None.
        """
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()
                
    def forward(self, x):
        """Extract four multi-scale feature maps.

        Args:
            x: Input image tensor with shape ``[B, C, H, W]``.

        Returns:
            List of four feature maps from shallow to deep stages.
        """
        B = x.shape[0]
        outs = []

        # Stage 1 returns the highest-resolution feature map.
        x, H, W = self.patch_embed1.forward(x)
        for i, blk in enumerate(self.block1):
            x = blk.forward(x, H, W)
        x = self.norm1(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # Stage 2 halves the spatial resolution.
        x, H, W = self.patch_embed2.forward(x)
        for i, blk in enumerate(self.block2):
            x = blk.forward(x, H, W)
        x = self.norm2(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # Stage 3 provides mid-level semantic features.
        x, H, W = self.patch_embed3.forward(x)
        for i, blk in enumerate(self.block3):
            x = blk.forward(x, H, W)
        x = self.norm3(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # Stage 4 provides the deepest semantic feature map.
        x, H, W = self.patch_embed4.forward(x)
        for i, blk in enumerate(self.block4):
            x = blk.forward(x, H, W)
        x = self.norm4(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        return outs

class mit_b0(MixVisionTransformer):
    """MiT-B0 backbone variant."""

    def __init__(self, pretrained_path=None):
        """Create a MiT-B0 backbone.

        Args:
            pretrained_path: Optional checkpoint path for backbone weights.

        Returns:
            None.
        """
        super(mit_b0, self).__init__(
            embed_dims=[32, 64, 160, 256], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[2, 2, 2, 2], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1)
        if pretrained_path and os.path.exists(pretrained_path):
            print(f"[INFO] Load backbone weights from {pretrained_path}")
            self.load_state_dict(torch.load(pretrained_path), strict=False)

class mit_b1(MixVisionTransformer):
    """MiT-B1 backbone variant."""

    def __init__(self, pretrained_path=None):
        """Create a MiT-B1 backbone.

        Args:
            pretrained_path: Optional checkpoint path for backbone weights.

        Returns:
            None.
        """
        super(mit_b1, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[2, 2, 2, 2], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1)
        if pretrained_path and os.path.exists(pretrained_path):
            print(f"[INFO] Load backbone weights from {pretrained_path}")
            self.load_state_dict(torch.load(pretrained_path), strict=False)

class mit_b2(MixVisionTransformer):
    """MiT-B2 backbone variant."""

    def __init__(self, pretrained_path=None):
        """Create a MiT-B2 backbone.

        Args:
            pretrained_path: Optional checkpoint path for backbone weights.

        Returns:
            None.
        """
        super(mit_b2, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 4, 6, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1)
        if pretrained_path and os.path.exists(pretrained_path):
            print(f"[INFO] Load backbone weights from {pretrained_path}")
            self.load_state_dict(torch.load(pretrained_path), strict=False)

class mit_b3(MixVisionTransformer):
    """MiT-B3 backbone variant."""

    def __init__(self, pretrained_path=None):
        """Create a MiT-B3 backbone.

        Args:
            pretrained_path: Optional checkpoint path for backbone weights.

        Returns:
            None.
        """
        super(mit_b3, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 4, 18, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1)
        if pretrained_path and os.path.exists(pretrained_path):
            print(f"[INFO] Load backbone weights from {pretrained_path}")
            self.load_state_dict(torch.load(pretrained_path), strict=False)

class mit_b4(MixVisionTransformer):
    """MiT-B4 backbone variant."""

    def __init__(self, pretrained_path=None):
        """Create a MiT-B4 backbone.

        Args:
            pretrained_path: Optional checkpoint path for backbone weights.

        Returns:
            None.
        """
        super(mit_b4, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 8, 27, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1)
        if pretrained_path and os.path.exists(pretrained_path):
            print(f"[INFO] Load backbone weights from {pretrained_path}")
            self.load_state_dict(torch.load(pretrained_path), strict=False)

class mit_b5(MixVisionTransformer):
    """MiT-B5 backbone variant."""

    def __init__(self, pretrained_path=None):
        """Create a MiT-B5 backbone.

        Args:
            pretrained_path: Optional checkpoint path for backbone weights.

        Returns:
            None.
        """
        super(mit_b5, self).__init__(
            embed_dims=[64, 128, 320, 512], num_heads=[1, 2, 5, 8], mlp_ratios=[4, 4, 4, 4],
            qkv_bias=True, norm_layer=partial(nn.LayerNorm, eps=1e-6), depths=[3, 6, 40, 3], sr_ratios=[8, 4, 2, 1],
            drop_rate=0.0, drop_path_rate=0.1)
        if pretrained_path and os.path.exists(pretrained_path):
            print(f"[INFO] Load backbone weights from {pretrained_path}")
            self.load_state_dict(torch.load(pretrained_path), strict=False)
