# ==========================================
# 模型超参数配置文件 (Train/Test)
# ==========================================
train:
  batch_size: 4
  num_workers: 4
  epochs: 100
  num_classes: 9
  phi: "b0"                 # Segformer 版本 (b0~b5)
  resize_size: [640, 480]   # [W, H] 输入图像尺寸

  # 学习率设置
  lr_f: 5.0e-5              # 融合头学习率
  # lr_mfe: 5.0e-5            # MFE模块学习率
  lr_seg: 5.0e-5            # 分割头学习率
  lr_all: 5.0e-4            # 整体快速优化学习率

  # --- 微调的学习率（modify_2） ---
  # lr_all: 1.0e-5
  # lr_f: 1.0e-5
  # lr_seg: 1.0e-5
  # --- 微调的学习率（modify_2） ---

  # 元学习 (Meta-learning) 核心参数
  lambda_g: 0.1
  inner_lr: 1.0e-5          # 内循环 (Inner loop) 更新步长
  inner_every: 3            # 每隔几个 epoch 触发一次 Meta 更新
  inner_warmup: 10          # 前 W 个 epoch 作为预热，不做内更新
  
  use_amp: true             # 是否使用混合精度训练加速

test:
  batch_size: 1             # 测试时通常为 1
  num_workers: 4
  num_classes: 9
  phi: "b3"
  resize_size: [640, 480]